name: Notifica cuando esta rama se actualice

on:
  push:
    branches: [main]

jobs:
  alert:
    runs-on: ubuntu-latest
    steps:
      - name: Send email
        env:
          RESEND_API_KEY: ${{ secrets.SECRET_RESEND_API }}
        run: |
          npx resend-cli emails send \
            --from "onboarding@resend.dev" \
            --to "${{ secrets.SECRET_DESTINATARIOS }}" \
            --subject "test" \
            --html "<h1>aaaaaaaaaa</h1>"
