name: Pruebas de Automatización

# Define los eventos que activarán el workflow
on:
  push:
    branches: [ main ] # Ejecuta el workflow en pushes a la rama main
  schedule:
    # Ejecuta a las 12:00 UTC (8:00 AM hora de Venezuela) los lunes, miércoles y viernes
    - cron: '0 11 * * 2,4'

jobs:
  test:
    runs-on: ubuntu-latest # Define el tipo de runner que ejecutará el job

    steps:
      # Realiza el checkout del código fuente
      - name: Checkout Code
        uses: actions/checkout@v4

      # Configura Java 17 usando Temurin
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'

      # Cachea las dependencias de Maven para mejorar los tiempos de ejecución
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      # Ejecuta tests y genera reporte, filtrando por la etiqueta @AdServer
      - name: Run tests and generate report
        run: mvn test "-Dcucumber.filter.tags=@Amyr"

      # Comprime los reportes y capturas de pantalla en un archivo ZIP
      - name: Compress report and screenshots into a ZIP file
        run: |
          zip -r reporte.zip "Reporte 0"

      # Sube el archivo ZIP como un artefacto del workflow
      - name: Upload Extent Report ZIP
        uses: actions/upload-artifact@v3
        with:
          name: extent-report-zip
          path: reporte.zip

      # Envia un email con el reporte adjunto
      - name: Send email with zipped report
        uses: dawidd6/action-send-mail@v3.10.0
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.SECRET_EMAIL }} # Usa secretos para la autenticación
          password: ${{ secrets.SECRET_PASSWORD }}
          subject: Resultados de Automatización
          body: Se adjuntan los resultados de la última ejecución de pruebas.
          to:
          cc:
          from:
          ignore_cert: true
          attachments: reporte.zip